version: "3.3"
services:
  client:
    image: node:18.4.0-alpine3.16
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    entrypoint: ["yarn"]
    ports:
      - "8000:8000"
      - "4173:4173"
    command: ["dev"]

  yarn:
    image: node:18.4.0-alpine3.16
    working_dir: /home/node/app
    profiles: ["cli"]
    volumes:
      - ../.yarn-cache:/yarn-cache:rw
      - .:/home/node/app
    entrypoint: ["yarn"]
    environment:
      YARN_CACHE_FOLDER: "/yarn-cache"
