services:
  client:
    image: node:22-alpine3.19
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    entrypoint: ["yarn"]
    ports:
      - "8000:8000"
      - "4173:4173"
    command: ["dev"]

  yarn:
    image: node:22-alpine3.19
    working_dir: /home/node/app
    profiles: ["cli"]
    volumes:
      - .:/home/node/app
    entrypoint: ["yarn"]
