version: "3.3"
services:
  client:
    image: node:16.13.1-alpine3.14
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    entrypoint: ["yarn"]
    ports:
      - "8000:8000"
      - "5000:5000"
    command: ["dev"]

  yarn:
    image: node:16.13.1-alpine3.14
    working_dir: /home/node/app
    profiles: ['cli']
    volumes:
      - ../.yarn-cache:/yarn-cache:rw
      - ../.cache:/home/node/.cache/Cypress:rw
      - .:/home/node/app
    entrypoint: ["yarn"]
    environment:
      YARN_CACHE_FOLDER: "/yarn-cache"
