services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: xccup-client
    container_name: xccup-client
    env_file: ./client/.env
    restart: always
    depends_on:
      - server

    labels:
      traefik.enable: true
      traefik.http.routers.xccup.rule: "Host(`xccup.net`)"
      traefik.http.routers.xccup.entrypoints: websecure
      traefik.http.routers.xccup.tls.certresolver: myresolver
      traefik.http.routers.xccup.priority: 100
      traefik.docker.network: traefik

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: xccup-server
    container_name: xccup-server
    restart: always
    env_file: ./server/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/home/node/app/data
      - ./import:/home/node/app/import
    depends_on:
      - db
      - igc-xc-score

    labels:
      traefik.enable: true
      traefik.http.routers.xccup-api.rule: "Host(`xccup.net`) && PathPrefix(`/api`) || Host(`test.xccup.net`) && PathPrefix(`/api`)"
      traefik.http.routers.xccup-api.entrypoints: websecure
      traefik.http.routers.xccup-api.tls.certresolver: myresolver
      traefik.http.services.xccup-api.loadbalancer.server.port: 65090
      traefik.http.routers.xccup-api.priority: 200
      traefik.docker.network: traefik
    command: ./docker-entrypoint.sh

  igc-xc-score:
    container_name: igc-xc-score
    build:
      context: ./server/igc-xc-score
    image: xc-igc-score
    environment:
      NODE_ENV: production
    ports:
      - "127.0.0.1:3030:3030"

  db:
    image: postgis/postgis:13-3.1
    container_name: xccup-db
    restart: always
    env_file: ./server/.env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - xccup-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: xccup-db-admin
    restart: always
    env_file: ./server/.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    labels:
      traefik.enable: true
      traefik.http.routers.xccup-pg-admin.rule: "Host(`pga.xccup.net`)"
      traefik.http.routers.xccup-pg-admin.entrypoints: websecure
      traefik.http.routers.xccup-pg-admin.tls.certresolver: myresolver
      traefik.port: 65080
      traefik.http.routers.xccup-pg-admin.priority: 100
      traefik.docker.network: traefik

volumes:
  xccup-db:
  pgadmin-data:

networks:
  default:
    name: traefik
    external: true
