version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: xccup-client-test
    container_name: xccup-client-test
    env_file: ./client/.env
    restart: always
 
    labels:
      traefik.enable: true
      traefik.http.routers.xccup-test.rule: "Host(`test.xccup.net`)"
      traefik.http.routers.xccup-test.entrypoints: websecure
      traefik.http.routers.xccup-test.tls.certresolver: myresolver
      traefik.http.routers.xccup-test.priority: 200
      traefik.docker.network: traefik

networks:
  default:
    external:
      name: traefik
