version: "3.8"

# To use the dicebear image clone the repo https://github.com/dicebear/api into the root folder of xccup.net

services:
  dicebear:
      build:
        context: ./api
        dockerfile: Dockerfile
      image: xccup-dicebear
      container_name: xccup-dicebear
      restart: always

      labels:
        traefik.enable: true
        traefik.http.routers.xccup-dicebear.rule: "Host(`v2202201165351174766.goodsrv.de`) && PathPrefix(`/dicebear`)"
        traefik.http.middlewares.dicebearpathstrip.stripprefix.prefixes: "/dicebear"
        traefik.http.routers.xccup-dicebear.middlewares: dicebearpathstrip@docker
        traefik.http.middlewares.dicebearpathstrip.stripprefix.forceslash: true
        traefik.http.routers.xccup-dicebear.entrypoints: websecure
        traefik.http.routers.xccup-dicebear.tls.certresolver: myresolver
        traefik.port: 3000
        traefik.http.routers.xccup-dicebear.priority: 200
        traefik.docker.network: traefik
        
networks:
  default:
    name: traefik

