version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - xccup-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: db_admin
    restart: always
    env_file: .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD
    ports:
      - 65080:80
    networks:
      - xccup-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: xcccup/api
    container_name: api
    restart: always
    env_file: .env
    environment:
      - SERVER_PORT=$SERVER_PORT
      - NODE_ENV=development
    ports:
      - "80:80"
    volumes:
      - .:/app
    networks:
      - xccup-network
    depends_on:
      - db
    command: ./docker-entrypoint.sh

networks:
  xccup-network:
    driver: bridge
