version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: db-admin
    restart: always
    env_file: .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD
    ports:
      - 65080:80
    networks:
      - backend

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: xccup/server
    container_name: server
    restart: always
    env_file: .env
    environment:
      - SERVER_PORT=$SERVER_PORT
      - NODE_ENV=production
    expose:
      - 65090
    networks:
      - frontend
      - backend
    depends_on:
      - db
    labels:
      traefik.enable: true
      traefik.http.routers.xccup-api.rule: "Host(`xccup.lurb.org`)"
      traefik.http.routers.xccup-api.entrypoints: websecure
      traefik.http.routers.xccup-api.tls.certresolver: myresolver
      traefik.port: 65090
      traefik.docker.network: traefik
    command: ./docker-entrypoint.sh

volumes:
  db:

networks:
  backend:
    driver: bridge

  frontend:
    external:
      name: traefik
