# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: kai.wpkt@gmail.com
        PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
    ports:
      - 65080:80