version: "3.3"

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: db
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - xccup-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: xccup/server
    container_name: server
    environment:
      - SERVER_PORT=$SERVER_PORT
      - NODE_ENV=CI
    ports:
      - "3000:65090"
    volumes:
      - .:/home/node/app
    networks:
      - xccup-network
    depends_on:
      - db
    command: ./docker-entrypoint.sh

  yarn:
    build:
      context: .
      dockerfile: Dockerfile
    image: xccup/yarn
    profiles: ['cli']
    volumes:
      - .:/home/node/app
    entrypoint: ["yarn"]

volumes:
  db:
  pgadmin-data:

networks:
  xccup-network:
    driver: bridge
