version: "3.9"

services:
  db:
    image: odidev/postgis:13-3.1
    container_name: db
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - xccup-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: db-admin
    restart: always
    env_file: .env
    ports:
      - 65080:80
    networks:
      - xccup-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: xccup/server
    container_name: server
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=development
    ports:
      - "3000:65090"
    volumes:
      - .:/home/node/app
    networks:
      - xccup-network
    depends_on:
      - db

  npm:
    image: node:20-alpine3.19
    working_dir: /home/node/app
    profiles: ["cli"]
    volumes:
      - .:/home/node/app
    entrypoint: [""]

volumes:
  db:
  pgadmin-data:

networks:
  xccup-network:
    driver: bridge
