version: "3.9"

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: db
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - xccup-network

  pgadmin:
    image: dpage/pgadmin4:6.3
    container_name: db-admin
    restart: always
    env_file: .env
    ports:
      - 65080:80
    networks:
      - xccup-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: xccup/server
    container_name: server
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=development
    ports:
      - "3000:65090"
    volumes:
      - .:/home/node/app
    networks:
      - xccup-network
    depends_on:
      - db

  yarn:
    image: node:17.8.0-alpine3.15
    working_dir: /home/node/app
    profiles: ["cli"]
    volumes:
      - ../.yarn-cache:/yarn-cache:rw
      - .:/home/node/app
    entrypoint: ["yarn"]
    environment:
      YARN_CACHE_FOLDER: "/yarn-cache"

volumes:
  db:
  pgadmin-data:

networks:
  xccup-network:
    driver: bridge
