name: XCCup E2E Deployment
on: workflow_dispatch
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Login via SSH, pull changes from "main", build docker images and check afterwards the log
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/xccup.net
            git pull
            docker-compose -f docker-compose-prod.yml up -d --force-recreate --build
            docker logs -n 10 xccup-server
            docker logs -n 10 xccup-client
